services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    user: node
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/workspace/
      - node_modules:/workspace/node_modules
    tty: true
    init: true
  mysql:
    image: mysql
    env_file:
      - .env
    volumes:
      - sql-data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    env_file:
      - .env
    ports:
      - 8080:80
volumes:
  node_modules:
  sql-data: